services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_dB=healthcare_app_dbs'
      - 'POSTGRES_USER=netra'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5436:5432'
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: unless-stopped


volumes:
  pgdata: